name: Build Google Shopping Sync Image

on:
  push:
    branches:
      - main
    paths:
      - 'google-shopping-sync/**'
      - '.github/workflows/build-google-shopping-sync.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/joshlopes/google-shopping-sync

      - name: Build and push for aarch64
        uses: docker/build-push-action@v5
        with:
          context: ./google-shopping-sync
          push: true
          platforms: linux/arm64
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/aarch64-base:3.15
          tags: ghcr.io/joshlopes/google-shopping-sync/aarch64:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push for amd64
        uses: docker/build-push-action@v5
        with:
          context: ./google-shopping-sync
          push: true
          platforms: linux/amd64
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.15
          tags: ghcr.io/joshlopes/google-shopping-sync/amd64:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push for armhf
        uses: docker/build-push-action@v5
        with:
          context: ./google-shopping-sync
          push: true
          platforms: linux/arm/v6
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/armhf-base:3.15
          tags: ghcr.io/joshlopes/google-shopping-sync/armhf:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push for armv7
        uses: docker/build-push-action@v5
        with:
          context: ./google-shopping-sync
          push: true
          platforms: linux/arm/v7
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/armv7-base:3.15
          tags: ghcr.io/joshlopes/google-shopping-sync/armv7:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push for i386
        uses: docker/build-push-action@v5
        with:
          context: ./google-shopping-sync
          push: true
          platforms: linux/386
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/i386-base:3.15
          tags: ghcr.io/joshlopes/google-shopping-sync/i386:latest
          labels: ${{ steps.meta.outputs.labels }}
